# Generated by Django 6.1.1 on 2026-09-25 18:18

import django.db.models.deletion
import financeiro.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Familiar')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('codigo_convite', models.CharField(default=financeiro.models.gerar_codigo_convite, max_length=10, unique=True, verbose_name='Código de Convite da Família')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Familiar',
                'verbose_name_plural': 'Familiares',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Rendimento / Entrada'), ('SAIDA', 'Despesa / Saída')], max_length=10)),
                ('familiar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_customizadas', to='financeiro.familiar')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Aposentadoria / Benefício)'), ('SAIDA', 'Saída (Despesa / Compra)')], default='SAIDA', max_length=10, verbose_name='Tipo de Lançamento')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição / Finalidade')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('data', models.DateField(verbose_name='Data do Lançamento')),
                ('comprador', models.CharField(help_text='Ex: Jean Viana, Cuidadora Maria, etc.', max_length=120, verbose_name='Responsável / Comprador')),
                ('forma_pagamento', models.CharField(choices=[('DEBITO', 'Cartão de Débito'), ('CREDITO', 'Cartão de Crédito'), ('PIX', 'PIX'), ('DINHEIRO', 'Dinheiro em Espécie'), ('TRANSFERENCIA', 'Transferência Bancária')], default='DEBITO', max_length=20, verbose_name='Forma de Pagamento')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/%Y/%m/', verbose_name='Nota Fiscal / Comprovante (PDF ou Imagem)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='financeiro.categoria', verbose_name='Categoria')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='financeiro.familiar', verbose_name='Familiar')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='VinculoFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('GESTOR', 'Gestor Principal (Controle Total)'), ('MEMBRO', 'Membro Familiar (Lança despesas e visualiza)')], default='MEMBRO', max_length=15)),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando Aprovação do Gestor'), ('APROVADO', 'Aprovado / Ativo'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=15)),
                ('solicitado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_vinculados', to='financeiro.familiar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vínculo Familiar',
                'verbose_name_plural': 'Vínculos Familiares',
                'unique_together': {('usuario', 'familiar')},
            },
        ),
    ]
